from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO

def generate_pdf_report(doc_data):
    """
    Generates a PDF report for a analyzed document.
    doc_data: dict with keys 'filename', 'results' (list of clauses)
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e40af'), # Blue-800
        spaceAfter=30
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.gray,
        spaceAfter=20
    )
    
    # Content
    elements = []
    
    # Header / Title
    elements.append(Paragraph("Legalese.ai Risk Report", title_style))
    elements.append(Paragraph(f"Document: {doc_data['filename']}", subtitle_style))
    elements.append(Spacer(1, 0.2 * inch))
    
    # Risk Summary
    high_risks = len([r for r in doc_data['results'] if r['risk'] == 'High'])
    medium_risks = len([r for r in doc_data['results'] if r['risk'] == 'Medium'])
    low_risks = len([r for r in doc_data['results'] if r['risk'] == 'Low'])
    
    summary_text = f"""
    <b>Risk Summary:</b><br/>
    High Risk: {high_risks}<br/>
    Medium Risk: {medium_risks}<br/>
    Low Risk: {low_risks}
    """
    elements.append(Paragraph(summary_text, styles['Normal']))
    elements.append(Spacer(1, 0.3 * inch))
    
    # Detailed Analysis Table
    data = [['Risk Level', 'Clause', 'Analysis']]
    
    for item in doc_data['results']:
        # Color coding text for risk
        risk_color = colors.black
        if item['risk'] == 'High':
            risk_color = colors.red
        elif item['risk'] == 'Medium':
            risk_color = colors.orange
        elif item['risk'] == 'Low':
            risk_color = colors.green
            
        risk_cell = Paragraph(f"<font color='{risk_color}'><b>{item['risk']}</b></font>", styles['Normal'])
        clause_cell = Paragraph(item['text'][:200] + "..." if len(item['text']) > 200 else item['text'], styles['Normal'])
        analysis_cell = Paragraph(item['explanation'], styles['Normal'])
        
        data.append([risk_cell, clause_cell, analysis_cell])
        
    # Table Styling
    table = Table(data, colWidths=[1.0*inch, 3.0*inch, 3.5*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')), # Slate-100
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1e293b')), # Slate-800
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')), # Slate-200
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    
    elements.append(table)
    
    # Footer disclaimer
    elements.append(Spacer(1, 0.5 * inch))
    disclaimer = "This report is generated by AI and does not constitute legal advice."
    elements.append(Paragraph(disclaimer, ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)))
    
    # Build
    doc.build(elements)
    buffer.seek(0)
    return buffer
